# Generated by Django 5.1.3 on 2025-01-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[(0, "easy"), (1, "medium"), (2, "hard")],
                default=0,
                max_length=9,
            ),
        ),
    ]
